name: Build and Push Docker Images

on:
  push:
    branches:
      - main   

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: reyewkha/craftista-frontend:latest

      - name: Build and push catalogue image
        uses: docker/build-push-action@v4
        with:
          context: ./catalogue
          push: true
          tags: reyewkha/craftista-catalogue:latest

      - name: Build and push recco image
        uses: docker/build-push-action@v4
        with:
          context: ./recommendation
          push: true
          tags: reyewkha/craftista-recco:latest

      - name: Build and push voting image
        uses: docker/build-push-action@v4
        with:
          context: ./voting
          push: true
          tags: reyewkha/craftista-voting:latest
